name: PR Check

on:
  pull_request:
    branches: [ "master" ]

jobs:
  Validation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Setup environment variables
      uses: SpicyPizza/create-envfile@v2.0.3
      with:
        envkey_PORT: ${{vars.CI_PORT}}
        envkey_DB_NAME: ${{vars.CI_DB_NAME}}
        envkey_DB_PORT: ${{vars.CI_DB_PORT}}
        envkey_DB_HOST: ${{vars.CI_DB_HOST}}
        envkey_DB_USER_NAME: ${{vars.CI_DB_USER_NAME}}
        envkey_DB_PASSWORD: ${{vars.CI_DB_PASSWORD}}
        envkey_JWT_ACCESS_SECRET: ${{vars.CI_JWT_ACCESS_SECRET}}
        envkey_JWT_REFRESH_SECRET: ${{vars.CI_JWT_REFRESH_SECRET}}
        envkey_JWT_ACCESS_EXPIRATION_TIME: ${{vars.CI_JWT_ACCESS_EXPIRATION_TIME}}
        envkey_JWT_REFRESH_EXPIRATION_TIME: ${{vars.CI_JWT_REFRESH_EXPIRATION_TIME}}
        envkey_MAILER_USER: ${{vars.CI_MAILER_USER}}
        envkey_MAILER_PASSWORD: ${{vars.CI_MAILER_PASSWORD}}
        file_name: .env.test

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Typescript
      run: npm run tsc

    - name: Unit Tests
      run: npm run test
