name: PR Check

on:
  pull_request:
    branches: [ "master" ]

jobs:
  Validation:
    runs-on: ubuntu-latest
    environment: ci

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup environment variables
      uses: SpicyPizza/create-envfile@v2.0.3
      with:
        envkey_PORT: ${{secrets.PORT}}
        envkey_DB_NAME: ${{secrets.DB_NAME}}
        envkey_DB_PORT: ${{secrets.DB_PORT}}
        envkey_DB_HOST: ${{secrets.DB_HOST}}
        envkey_DB_USER_NAME: ${{secrets.DB_USER_NAME}}
        envkey_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        envkey_JWT_ACCESS_SECRET: ${{secrets.JWT_ACCESS_SECRET}}
        envkey_JWT_REFRESH_SECRET: ${{secrets.JWT_REFRESH_SECRET}}
        envkey_JWT_ACCESS_EXPIRATION_TIME: ${{secrets.JWT_ACCESS_EXPIRATION_TIME}}
        envkey_JWT_REFRESH_EXPIRATION_TIME: ${{secrets.JWT_REFRESH_EXPIRATION_TIME}}
        envkey_MAILER_USER: ${{secrets.MAILER_USER}}
        envkey_MAILER_PASSWORD: ${{secrets.MAILER_PASSWORD}}

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Typescript
      run: npm run tsc

    - name: Unit Tests
      run: npm run test
